/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jorgealvarez_lab7;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Scanner;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeNode;

/**
 *
 * @author ofici
 */
public class VentanaPrincipalLab7 extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipalLab7() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ListarBg = new javax.swing.ButtonGroup();
        ModificarBg = new javax.swing.ButtonGroup();
        AgregarAlumnoJd = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        NombreAgregarAlumnoTf = new javax.swing.JTextField();
        NicknameAgregarAlumnoTf = new javax.swing.JTextField();
        AtaqueAgregarAlumnoTf = new javax.swing.JTextField();
        DefensaAgregarAlumnoTf = new javax.swing.JTextField();
        SaludAgregarAlumnoTf = new javax.swing.JTextField();
        ConfirmarAgregarAlumnoBt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        NumeroDeCuentaAgregarAlumnoTf = new javax.swing.JTextField();
        CarreraAgregarAlumnoTf = new javax.swing.JTextField();
        EdadAgregarAlumnoTf = new javax.swing.JTextField();
        AgregarGuerreroJd = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        NombreAgregarGuerreroTf = new javax.swing.JTextField();
        NicknameAgregarGuerreroTf = new javax.swing.JTextField();
        AtaqueAgregarGuerreroTf = new javax.swing.JTextField();
        DefensaAgregarGuerreroTf = new javax.swing.JTextField();
        SaludAgregarGuerreroTf = new javax.swing.JTextField();
        ConfirmarAgregarGuerreroJdBt = new javax.swing.JButton();
        PrincipalTp = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        DragonAgregarBt = new javax.swing.JButton();
        FenixAgregarBt = new javax.swing.JButton();
        HombreLoboAgregarBt = new javax.swing.JButton();
        MinotauroAgregarBt = new javax.swing.JButton();
        AlumnoAgregarBt = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaListar = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        ComboBoxModificar = new javax.swing.JComboBox<>();
        ActualizarControlesModificarBt = new javax.swing.JButton();
        EliminarModificarBt = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        RealizarVentaNuevaVentaBt = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        AbrirMn = new javax.swing.JMenuItem();
        GuardarMn = new javax.swing.JMenuItem();
        GuardarComoMn = new javax.swing.JMenuItem();
        SalirMn = new javax.swing.JMenuItem();

        jLabel8.setText("Ataque");

        jLabel9.setText("Nickname");

        jLabel10.setText("Defensa");

        jLabel11.setText("Salud");

        jLabel13.setText("Nombre");

        ConfirmarAgregarAlumnoBt.setText("Confirmar");
        ConfirmarAgregarAlumnoBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarAgregarAlumnoBtActionPerformed(evt);
            }
        });

        jLabel2.setText("Numero de cuenta");

        jLabel3.setText("Carrera");

        jLabel5.setText("Edad");

        javax.swing.GroupLayout AgregarAlumnoJdLayout = new javax.swing.GroupLayout(AgregarAlumnoJd.getContentPane());
        AgregarAlumnoJd.getContentPane().setLayout(AgregarAlumnoJdLayout);
        AgregarAlumnoJdLayout.setHorizontalGroup(
            AgregarAlumnoJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarAlumnoJdLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(AgregarAlumnoJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(AgregarAlumnoJdLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel12))
                    .addComponent(jLabel11)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addGap(57, 57, 57)
                .addGroup(AgregarAlumnoJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AgregarAlumnoJdLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ConfirmarAgregarAlumnoBt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(NombreAgregarAlumnoTf, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(NicknameAgregarAlumnoTf)
                    .addComponent(AtaqueAgregarAlumnoTf)
                    .addComponent(DefensaAgregarAlumnoTf)
                    .addComponent(SaludAgregarAlumnoTf)
                    .addComponent(NumeroDeCuentaAgregarAlumnoTf)
                    .addComponent(CarreraAgregarAlumnoTf)
                    .addComponent(EdadAgregarAlumnoTf))
                .addContainerGap())
        );
        AgregarAlumnoJdLayout.setVerticalGroup(
            AgregarAlumnoJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarAlumnoJdLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(AgregarAlumnoJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(NombreAgregarAlumnoTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarAlumnoJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(NicknameAgregarAlumnoTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarAlumnoJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(AtaqueAgregarAlumnoTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarAlumnoJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(DefensaAgregarAlumnoTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarAlumnoJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(SaludAgregarAlumnoTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(AgregarAlumnoJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AgregarAlumnoJdLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel12))
                    .addGroup(AgregarAlumnoJdLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(AgregarAlumnoJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NumeroDeCuentaAgregarAlumnoTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addGap(18, 18, 18)
                .addGroup(AgregarAlumnoJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CarreraAgregarAlumnoTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(AgregarAlumnoJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EdadAgregarAlumnoTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(ConfirmarAgregarAlumnoBt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel14.setText("Ataque");

        jLabel15.setText("Nickname");

        jLabel16.setText("Defensa");

        jLabel17.setText("Salud");

        jLabel48.setText("Nombre");

        ConfirmarAgregarGuerreroJdBt.setText("Confirmar");
        ConfirmarAgregarGuerreroJdBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarAgregarGuerreroJdBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AgregarGuerreroJdLayout = new javax.swing.GroupLayout(AgregarGuerreroJd.getContentPane());
        AgregarGuerreroJd.getContentPane().setLayout(AgregarGuerreroJdLayout);
        AgregarGuerreroJdLayout.setHorizontalGroup(
            AgregarGuerreroJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarGuerreroJdLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(AgregarGuerreroJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel48)
                    .addGroup(AgregarGuerreroJdLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel46))
                    .addComponent(jLabel17)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16))
                .addGap(57, 57, 57)
                .addGroup(AgregarGuerreroJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ConfirmarAgregarGuerreroJdBt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AgregarGuerreroJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(NombreAgregarGuerreroTf, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(NicknameAgregarGuerreroTf)
                        .addComponent(AtaqueAgregarGuerreroTf)
                        .addComponent(DefensaAgregarGuerreroTf)
                        .addComponent(SaludAgregarGuerreroTf)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AgregarGuerreroJdLayout.setVerticalGroup(
            AgregarGuerreroJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarGuerreroJdLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(AgregarGuerreroJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(NombreAgregarGuerreroTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarGuerreroJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(NicknameAgregarGuerreroTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarGuerreroJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(AtaqueAgregarGuerreroTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarGuerreroJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(DefensaAgregarGuerreroTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarGuerreroJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(SaludAgregarGuerreroTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel46)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ConfirmarAgregarGuerreroJdBt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PrincipalTp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                PrincipalTpStateChanged(evt);
            }
        });

        jLabel1.setText("Agregar Personas");

        DragonAgregarBt.setText("Dragón");
        DragonAgregarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DragonAgregarBtActionPerformed(evt);
            }
        });

        FenixAgregarBt.setText("Fénix");
        FenixAgregarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FenixAgregarBtActionPerformed(evt);
            }
        });

        HombreLoboAgregarBt.setText("Hombre Lobo");
        HombreLoboAgregarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HombreLoboAgregarBtActionPerformed(evt);
            }
        });

        MinotauroAgregarBt.setText("Minotauro");
        MinotauroAgregarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinotauroAgregarBtActionPerformed(evt);
            }
        });

        AlumnoAgregarBt.setText("Alumno");
        AlumnoAgregarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlumnoAgregarBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(DragonAgregarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(MinotauroAgregarBt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HombreLoboAgregarBt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FenixAgregarBt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                    .addComponent(AlumnoAgregarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(674, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(DragonAgregarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(FenixAgregarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(HombreLoboAgregarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MinotauroAgregarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AlumnoAgregarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(196, Short.MAX_VALUE))
        );

        PrincipalTp.addTab("Agregar", jPanel2);

        jLabel4.setText("Guerreros");

        TablaListar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "ID", "Edad", "Nacionalidad", "Lugar de nacimiento", "Color de piel"
            }
        ));
        jScrollPane4.setViewportView(TablaListar);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                .addContainerGap())
        );

        PrincipalTp.addTab("Listar", jPanel5);

        jLabel6.setText("Personas");

        ActualizarControlesModificarBt.setText("Seleccionar");
        ActualizarControlesModificarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarControlesModificarBtActionPerformed(evt);
            }
        });

        EliminarModificarBt.setText("Eliminar");
        EliminarModificarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarModificarBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboBoxModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(29, 29, 29)
                .addComponent(ActualizarControlesModificarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EliminarModificarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(205, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ActualizarControlesModificarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EliminarModificarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(448, Short.MAX_VALUE))
        );

        PrincipalTp.addTab("Modificar", jPanel3);

        RealizarVentaNuevaVentaBt.setText("Realizar Venta");
        RealizarVentaNuevaVentaBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RealizarVentaNuevaVentaBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(575, Short.MAX_VALUE)
                .addComponent(RealizarVentaNuevaVentaBt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(268, Short.MAX_VALUE)
                .addComponent(RealizarVentaNuevaVentaBt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(217, 217, 217))
        );

        jTabbedPane2.addTab("Nueva venta", jPanel6);

        jRadioButton3.setText("Venta de baleadas");

        jRadioButton4.setText("Ventas de gatos");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", "", " "
            }
        ));
        jScrollPane10.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jRadioButton3)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 786, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Reportes", jPanel7);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        PrincipalTp.addTab("Batallas", jPanel4);

        jMenu1.setText("Archivo");

        AbrirMn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        AbrirMn.setText("Abrir");
        AbrirMn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirMnActionPerformed(evt);
            }
        });
        jMenu1.add(AbrirMn);

        GuardarMn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        GuardarMn.setText("Guardar");
        GuardarMn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarMnActionPerformed(evt);
            }
        });
        jMenu1.add(GuardarMn);

        GuardarComoMn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        GuardarComoMn.setText("Guardar como");
        GuardarComoMn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarComoMnActionPerformed(evt);
            }
        });
        jMenu1.add(GuardarComoMn);

        SalirMn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        SalirMn.setText("Salir");
        SalirMn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirMnActionPerformed(evt);
            }
        });
        jMenu1.add(SalirMn);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PrincipalTp)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PrincipalTp, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DragonAgregarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DragonAgregarBtActionPerformed
        // TODO add your handling code here:
        Modificar = 0;
        Tipo = 0;
        AgregarGuerreroJd.setVisible(true);
        NombreAgregarGuerreroTf.setText("");
        NicknameAgregarGuerreroTf.setText("");
        AtaqueAgregarGuerreroTf.setText("");
        DefensaAgregarGuerreroTf.setText("");
        SaludAgregarGuerreroTf.setText("");
        AgregarGuerreroJd.pack();
    }//GEN-LAST:event_DragonAgregarBtActionPerformed
    //0-Jefe de Cocina 1-Jefe de Baleadas 2-Jefe de Gatos
    private void ConfirmarAgregarAlumnoBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarAgregarAlumnoBtActionPerformed
        // TODO add your handling code here:
        int pos;
        if (Modificar == 0) {
            Guerreros.add(new Alumno());
            pos = Guerreros.size() - 1;
        } else {
            pos = ComboBoxModificar.getSelectedIndex();
        }

        Guerreros.get(pos).setNombre(NombreAgregarGuerreroTf.getText());
        Guerreros.get(pos).setNickname(NicknameAgregarGuerreroTf.getText());
        try {
            Guerreros.get(pos).setAtaque(Float.parseFloat(AtaqueAgregarGuerreroTf.getText()));
        } catch (Exception e) {
        }
        try {
            Guerreros.get(pos).setDefensa(Float.parseFloat(DefensaAgregarGuerreroTf.getText()));
        } catch (Exception e) {
        }
        try {
            Guerreros.get(pos).setSalud(Float.parseFloat(SaludAgregarGuerreroTf.getText()));
        } catch (Exception e) {
        }
        ((Alumno) Guerreros.get(pos)).setNumeroDeCuenta(NumeroDeCuentaAgregarAlumnoTf.getText());
        ((Alumno) Guerreros.get(pos)).setCarrera(CarreraAgregarAlumnoTf.getText());
        ((Alumno) Guerreros.get(pos)).setEdad(Integer.parseInt(EdadAgregarAlumnoTf.getText()));
        AgregarAlumnoJd.dispose();
    }//GEN-LAST:event_ConfirmarAgregarAlumnoBtActionPerformed

    private void HombreLoboAgregarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HombreLoboAgregarBtActionPerformed
        // TODO add your handling code here:
        Modificar = 0;
        Tipo = 2;
        AgregarGuerreroJd.setVisible(true);
        NombreAgregarGuerreroTf.setText("");
        NicknameAgregarGuerreroTf.setText("");
        AtaqueAgregarGuerreroTf.setText("");
        DefensaAgregarGuerreroTf.setText("");
        SaludAgregarGuerreroTf.setText("");
        AgregarGuerreroJd.pack();
    }//GEN-LAST:event_HombreLoboAgregarBtActionPerformed

    private void MinotauroAgregarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinotauroAgregarBtActionPerformed
        // TODO add your handling code here:
        Modificar = 0;
        Tipo = 3;
        AgregarGuerreroJd.setVisible(true);
        NombreAgregarGuerreroTf.setText("");
        NicknameAgregarGuerreroTf.setText("");
        AtaqueAgregarGuerreroTf.setText("");
        DefensaAgregarGuerreroTf.setText("");
        SaludAgregarGuerreroTf.setText("");
        AgregarGuerreroJd.pack();
    }//GEN-LAST:event_MinotauroAgregarBtActionPerformed

    private void FenixAgregarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FenixAgregarBtActionPerformed
        // TODO add your handling code here:
        Modificar = 0;
        Tipo = 1;
        AgregarGuerreroJd.setVisible(true);
        NombreAgregarGuerreroTf.setText("");
        NicknameAgregarGuerreroTf.setText("");
        AtaqueAgregarGuerreroTf.setText("");
        DefensaAgregarGuerreroTf.setText("");
        SaludAgregarGuerreroTf.setText("");
        AgregarGuerreroJd.pack();
    }//GEN-LAST:event_FenixAgregarBtActionPerformed

    
    private void ActualizarControlesModificarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarControlesModificarBtActionPerformed
        // TODO add your handling code here:
        Modificar = 1;
        int pos = ComboBoxModificar.getSelectedIndex();
        if (Guerreros.get(pos)instanceof Alumno) {
            AgregarAlumnoJd.setVisible(true);
        }else{
            AgregarGuerreroJd.setVisible(true);
        }
    }//GEN-LAST:event_ActualizarControlesModificarBtActionPerformed

    private void GuardarMnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarMnActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_GuardarMnActionPerformed

    private void PrincipalTpStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_PrincipalTpStateChanged
        // TODO add your handling code here:
        if (PrincipalTp.getSelectedIndex() == 1) {
            TablaListar.setModel(new javax.swing.table.DefaultTableModel(
                    new Object[][]{},
                    new String[]{
                        "Nombre", "Nickname", "Ataque", "Defensa", "Salud"
                    }
            ));
            DefaultTableModel modelo = (DefaultTableModel) TablaListar.getModel();
            for (Guerrero t : Guerreros) {
                Object[] fila = {
                    t.getNombre(),
                    t.getNickname(),
                    t.getAtaque(),
                    t.getDefensa(),
                    t.getSalud()};
                modelo.addRow(fila);
            }
            TablaListar.setModel(modelo);
        }
        if (PrincipalTp.getSelectedIndex() == 2) {
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            for (Guerrero t : Guerreros) {
                modelo.addElement(t);
            }
            ComboBoxModificar.setModel(modelo);
        }
    }//GEN-LAST:event_PrincipalTpStateChanged

    private void SalirMnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirMnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_SalirMnActionPerformed
    String DirectorioAbrir = "";
    Object Ruta;
    private void AbrirMnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirMnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_AbrirMnActionPerformed

    private void EliminarModificarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarModificarBtActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_EliminarModificarBtActionPerformed

    private void GuardarComoMnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarComoMnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_GuardarComoMnActionPerformed

    private void ConfirmarAgregarGuerreroJdBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarAgregarGuerreroJdBtActionPerformed
        // TODO add your handling code here:
        int pos;
        if (Modificar == 0) {
            if (Tipo == 0) {
                Guerreros.add(new Dragon());
            }
            if (Tipo == 1) {
                Guerreros.add(new Fenix());
            }
            if (Tipo == 2) {
                Guerreros.add(new HombreLobo());
            }
            if (Tipo == 3) {
                Guerreros.add(new Minotauro());
            }
            if (Tipo == 4) {
                Guerreros.add(new Alumno());
            }
            pos = Guerreros.size() - 1;
        } else {
            pos = ComboBoxModificar.getSelectedIndex();
        }

        Guerreros.get(pos).setNombre(NombreAgregarGuerreroTf.getText());
        Guerreros.get(pos).setNickname(NicknameAgregarGuerreroTf.getText());
        try {
            Guerreros.get(pos).setAtaque(Float.parseFloat(AtaqueAgregarGuerreroTf.getText()));
        } catch (Exception e) {
        }
        try {
            Guerreros.get(pos).setDefensa(Float.parseFloat(DefensaAgregarGuerreroTf.getText()));
        } catch (Exception e) {
        }
        try {
            Guerreros.get(pos).setSalud(Float.parseFloat(SaludAgregarGuerreroTf.getText()));
        } catch (Exception e) {
        }
        AgregarGuerreroJd.dispose();
    }//GEN-LAST:event_ConfirmarAgregarGuerreroJdBtActionPerformed

    private void AlumnoAgregarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlumnoAgregarBtActionPerformed
        // TODO add your handling code here:
        Modificar = 0;
        Tipo = 4;
        AgregarAlumnoJd.setVisible(true);
        NombreAgregarGuerreroTf.setText("");
        NicknameAgregarAlumnoTf.setText("");
        AtaqueAgregarAlumnoTf.setText("");
        DefensaAgregarAlumnoTf.setText("");
        SaludAgregarAlumnoTf.setText("");
        AgregarAlumnoJd.pack();
    }//GEN-LAST:event_AlumnoAgregarBtActionPerformed

    private void RealizarVentaNuevaVentaBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RealizarVentaNuevaVentaBtActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_RealizarVentaNuevaVentaBtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalLab7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalLab7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalLab7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalLab7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipalLab7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AbrirMn;
    private javax.swing.JButton ActualizarControlesModificarBt;
    private javax.swing.JDialog AgregarAlumnoJd;
    private javax.swing.JDialog AgregarGuerreroJd;
    private javax.swing.JButton AlumnoAgregarBt;
    private javax.swing.JTextField AtaqueAgregarAlumnoTf;
    private javax.swing.JTextField AtaqueAgregarGuerreroTf;
    private javax.swing.JTextField CarreraAgregarAlumnoTf;
    private javax.swing.JComboBox<String> ComboBoxModificar;
    private javax.swing.JButton ConfirmarAgregarAlumnoBt;
    private javax.swing.JButton ConfirmarAgregarGuerreroJdBt;
    private javax.swing.JTextField DefensaAgregarAlumnoTf;
    private javax.swing.JTextField DefensaAgregarGuerreroTf;
    private javax.swing.JButton DragonAgregarBt;
    private javax.swing.JTextField EdadAgregarAlumnoTf;
    private javax.swing.JButton EliminarModificarBt;
    private javax.swing.JButton FenixAgregarBt;
    private javax.swing.JMenuItem GuardarComoMn;
    private javax.swing.JMenuItem GuardarMn;
    private javax.swing.JButton HombreLoboAgregarBt;
    private javax.swing.ButtonGroup ListarBg;
    private javax.swing.JButton MinotauroAgregarBt;
    private javax.swing.ButtonGroup ModificarBg;
    private javax.swing.JTextField NicknameAgregarAlumnoTf;
    private javax.swing.JTextField NicknameAgregarGuerreroTf;
    private javax.swing.JTextField NombreAgregarAlumnoTf;
    private javax.swing.JTextField NombreAgregarGuerreroTf;
    private javax.swing.JTextField NumeroDeCuentaAgregarAlumnoTf;
    private javax.swing.JTabbedPane PrincipalTp;
    private javax.swing.JButton RealizarVentaNuevaVentaBt;
    private javax.swing.JMenuItem SalirMn;
    private javax.swing.JTextField SaludAgregarAlumnoTf;
    private javax.swing.JTextField SaludAgregarGuerreroTf;
    private javax.swing.JTable TablaListar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    static ArrayList<Guerrero> Guerreros = new ArrayList();
    static int Modificar, posModificar;
    static int Tipo;
}
